### ISSUE TITLE
deadlock while using the concurrent.futures.ProcessPoolExecutor

### ISSUE THREAD

**Issue by lrlunin** [elarivie/pyReaderWriterLock#16]
Hello,

first of all I would like to thank you for developing and maintaining this package. Especially when the CPython developers claimed that [there will be no built-in RWLock](https://github.com/python/cpython/issues/53046#event-10112098210).

I was happy to use `ProcessPoolExecutor` feature from python `concurrent.futures` package. I used the following code to initialize the generator:
```python
manager = multiprocessing.Manager()
lock_gen = rwlock.RWLockWrite(lock_factory=manager.Lock)
```
but it looks to be not enough since the counters inside of the Locks are not accessible properly from the multiple processes.

I guess it will be enough to replace all counters with [`multiprocessing.Value`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.managers.SyncManager.Value) proxies in order to make them synchronized among threads.

Do you have any ideas if it will not be working or any other concerns? If this solution looks fine for you I could make a pull request to fix this.

Thanks in advance.

**Comment by elarivie** [comment]
Hello @lrlunin,

Thank you for your kind words.

Regarding your suggestion, I don't like the idea of blindly changing all internal integers to 'multiprocessing.Value' since it would introduce an unnecessary hard dependency on 'multiprocessing' and would probably also impact performance.

That being said, I'm genuinely interested in exploring a solution that accommodates your use case without compromising the library's current efficiency and interface.

One thought I've had while reading your suggestion would be to enhance the readerwriterlock's constructor. Alongside the existing 'lock_factory' parameter, there could be an 'int_factory' parameter. By default it would use the built-in int, preserving compatibility while allowing the use of alternative integer types for specialized use cases like yours.

It's worth noting that while integers are your primary concern, the library also uses boolean values. This raises the question of whether a bool_factory might be necessary as well. I'd appreciate your insights on this aspect as you probably have more experience with the library 'multiprocessing' than me.

Regarding your offer of contributing through a Pull Request, I never ignore suggestion nor pull request, they are welcome.

**Additionally:** @lrlunin if you could provide test cases or some implementation of multiprocessing scenarios that highlight the issue so I can use them for experimentation this would be appreciated.

Best regards
