### ISSUE TITLE
Reentrant locks

### ISSUE THREAD

**Issue by marcsello** [elarivie/pyReaderWriterLock#5]
It would be nice to have support for reentrant locks.
Similar to RLock in the Python standard library: https://docs.python.org/3.8/library/threading.html#rlock-objects

This would be very useful in the following scenario:
```python
from readwriterlock import rwlock 

class Example:
    def __init__(self):
         self._lock = rwlock.RRWLockFair()

    def update_everything(self):
        with self._lock.get_wlock():
            #  update some local variables maybe
            self.update_one_thing()
            self.update_other_thing()

    def update_one_thing(self):
        with self._lock.get_wlock():
            #  update stuff

    def update_other_thing(self):
        with self._lock.get_wlock():
            #  update stuff

```
Calling `update_everything` in the above screnario would cause a dead-lock without reentrant locks.

**Comment by elarivie** [comment]
Hello @marcsello,

Sorry but I don't plan to add the feature of re-entrant locks (aka recursive locks).

Here are the reasons why:

1. They would be a kind of lock which would add overhead (time and memory) and in exchange you would not gain any benefits.

2. _My personal opinion_ is that re-entrant locks are a hack and should not be use, code using a re-entrant lock should be flagged as bug

3. Code can always be written differently to not need re-entrant version of a lock


**For example:** Here is your above scenario slightly modified so that it is multithread safe, does not deadlock and does not require re-entrant lock:

```python
from readwriterlock import rwlock

class Example:
    def __init__(self):
         self._lock = rwlock.RWLockFair()

    def _update_one_thing(self):
        #  update stuff

    def _update_other_thing(self):
        #  update stuff

    def update_one_thing(self):
        with self._lock.gen_wlock():
            self._update_one_thing()

    def update_other_thing(self):
        with self._lock.gen_wlock():
            self._update_other_thing()

    def update_everything(self):
        with self._lock.gen_wlock():
            #  update some local variables maybe
            self._update_one_thing()
            self._update_other_thing()


```

**Comment by marcsello** [comment]
Thank you for your reply!
Altrough I believe this adds unecessary complexity to the program code, I do understand, and accept your point.
In that case I think it's worth adding a notice about this in the documentation. Not just that re-entrant locks are not going to be a thing, but also recommend a solution like yours for everyone looking to solve similar problems. :)
